services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: squadrun
      POSTGRES_USER: squadrun
      POSTGRES_PASSWORD: squadrunpass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    command: >
      sh -c "python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SECRET_KEY: "devsecretkey_change_me"
      DJANGO_DEBUG: "1"
      POSTGRES_DB: squadrun
      POSTGRES_USER: squadrun
      POSTGRES_PASSWORD: squadrunpass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      ALLOWED_HOSTS: "*"
      CORS_ORIGIN: "http://localhost:8081,http://localhost:19006"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  worker:
    build:
      context: ./backend
    command: >
      sh -c "python manage.py migrate &&
             celery -A backend.celery_app worker -l info"
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SECRET_KEY: "devsecretkey_change_me"
      DJANGO_DEBUG: "1"
      POSTGRES_DB: squadrun
      POSTGRES_USER: squadrun
      POSTGRES_PASSWORD: squadrunpass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      ALLOWED_HOSTS: "*"
      CORS_ORIGIN: "http://localhost:8081,http://localhost:19006"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - backend
      - redis
      - db

  beat:
    build:
      context: ./backend
    command: >
      sh -c "python manage.py migrate &&
             celery -A backend.celery_app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - ./backend:/app
    environment:
      DJANGO_SECRET_KEY: "devsecretkey_change_me"
      DJANGO_DEBUG: "1"
      POSTGRES_DB: squadrun
      POSTGRES_USER: squadrun
      POSTGRES_PASSWORD: squadrunpass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      ALLOWED_HOSTS: "*"
      CORS_ORIGIN: "http://localhost:8081,http://localhost:19006"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - backend
      - redis
      - db

  frontend:
    build:
      context: ./mobile
    volumes:
      - ./mobile:/app
      - /app/node_modules
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: "0.0.0.0"
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend

volumes:
  db_data:
