# Generated by Django 5.0.6 on 2025-10-29 20:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('members', models.ManyToManyField(related_name='squads', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_squads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SquadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='squads.squad')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SquadMemberStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak_weeks', models.IntegerField(default=0)),
                ('longest_streak_weeks', models.IntegerField(default=0)),
                ('last_week_achieved', models.BooleanField(default=False)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_stats', to='squads.squad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('squad', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SquadWeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(db_index=True)),
                ('target_distance_km', models.FloatField()),
                ('total_distance_km', models.FloatField(default=0)),
                ('achieved', models.BooleanField(default=False)),
                ('points_awarded_each_member', models.IntegerField(default=0)),
                ('closed_out', models.BooleanField(default=False)),
                ('unit_entered', models.CharField(default='km', max_length=5)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to='squads.squad')),
            ],
            options={
                'unique_together': {('squad', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyResultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('points_change', models.IntegerField()),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squads.squad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'squad', 'week_start_date')},
            },
        ),
    ]
