# Generated by Django 5.0.6 on 2025-10-29 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_squads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squad',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squad',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
