# Generated by Django 5.0.6 on 2025-10-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0002_squad_admins_squad_description_squad_is_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
